services:
  arti-socks-proxy:
    build:
      context: .
    image: ghcr.io/ntheile/arti-proxy:latest
    platform: linux/amd64
    container_name: arti-socks-proxy
    restart: always
    environment:
      HEALTHCHECK_URL: https://check.torproject.org/api/ip
      HEALTHCHECK_EXPECTED: '"IsTor":true'
      HEALTHCHECK_MAX_TIME: 30
      SOCKS_USERNAME: ${SOCKS_USERNAME:?SOCKS_USERNAME is required}
      SOCKS_PASSWORD: ${SOCKS_PASSWORD:?SOCKS_PASSWORD is required}
    ports:
      - "9150:9150/tcp"
    logging:
      driver: local
      options:
        max-size: 10m
        max-file: "3"
